"""
Utilities Module

This module provides shared utilities and helper functions for the Semantica framework.

Exports:
    - Logging utilities
    - Exception handling
    - Data validation
    - Helper functions
    - Constants and types
"""

from .logging import (
    setup_logging,
    get_logger,
    log_performance,
    log_error,
    log_data_quality,
    log_execution_time,
)
from .exceptions import (
    SemanticaError,
    ValidationError,
    ProcessingError,
    ConfigurationError,
    QualityError,
    handle_exception,
    format_exception,
)
from .validators import (
    validate_data,
    validate_config,
    validate_schema,
    validate_types,
    validate_required_fields,
    validate_string_constraints,
    validate_numeric_constraints,
    validate_list_constraints,
    validate_entity,
    validate_relationship,
    validate_file_path,
    validate_url,
    validate_email,
)
from .helpers import (
    format_data,
    clean_text,
    normalize_entities,
    hash_data,
    safe_filename,
    ensure_directory,
    read_json_file,
    write_json_file,
    get_file_size,
    format_timestamp,
    parse_timestamp,
    merge_dicts,
    chunk_list,
    flatten_dict,
    get_nested_value,
    set_nested_value,
    retry_on_error,
)
from .constants import (
    SUPPORTED_DOCUMENT_FORMATS,
    SUPPORTED_IMAGE_FORMATS,
    SUPPORTED_AUDIO_FORMATS,
    SUPPORTED_VIDEO_FORMATS,
    SUPPORTED_RDF_FORMATS,
    SUPPORTED_VECTOR_STORES,
    SUPPORTED_GRAPH_DBS,
    DEFAULT_CONFIG,
    ERROR_CODES,
    PERFORMANCE_THRESHOLDS,
    QUALITY_LEVELS,
    ENTITY_TYPES,
    RELATIONSHIP_TYPES,
    PROCESSING_STATUS,
    DATA_TYPES,
    API_ENDPOINTS,
    FILE_SIZE_LIMITS,
    RETRY_CONFIG,
    CACHE_CONFIG,
)
from .types import (
    # Type Aliases
    JSONType,
    EntityDict,
    RelationshipDict,
    ConfigDict,
    DataDict,
    # Enums
    EntityType,
    DataType,
    ProcessingStatus,
    QualityLevel,
    RelationshipType,
    # Data Classes
    Entity,
    Relationship,
    ProcessingResult,
    QualityMetrics,
    # Generic Types
    Result,
    BatchResult,
    # Type Guards
    is_entity_dict,
    is_relationship_dict,
    is_processing_result,
    # Conversion Functions
    entity_to_dict,
    dict_to_entity,
    relationship_to_dict,
    dict_to_relationship,
)

__all__ = [
    # Logging
    "setup_logging",
    "get_logger",
    "log_performance",
    "log_error",
    "log_data_quality",
    "log_execution_time",
    # Exceptions
    "SemanticaError",
    "ValidationError",
    "ProcessingError",
    "ConfigurationError",
    "QualityError",
    "handle_exception",
    "format_exception",
    # Validators
    "validate_data",
    "validate_config",
    "validate_schema",
    "validate_types",
    "validate_required_fields",
    "validate_string_constraints",
    "validate_numeric_constraints",
    "validate_list_constraints",
    "validate_entity",
    "validate_relationship",
    "validate_file_path",
    "validate_url",
    "validate_email",
    # Helpers
    "format_data",
    "clean_text",
    "normalize_entities",
    "hash_data",
    "safe_filename",
    "ensure_directory",
    "read_json_file",
    "write_json_file",
    "get_file_size",
    "format_timestamp",
    "parse_timestamp",
    "merge_dicts",
    "chunk_list",
    "flatten_dict",
    "get_nested_value",
    "set_nested_value",
    "retry_on_error",
    # Constants
    "SUPPORTED_DOCUMENT_FORMATS",
    "SUPPORTED_IMAGE_FORMATS",
    "SUPPORTED_AUDIO_FORMATS",
    "SUPPORTED_VIDEO_FORMATS",
    "SUPPORTED_RDF_FORMATS",
    "SUPPORTED_VECTOR_STORES",
    "SUPPORTED_GRAPH_DBS",
    "DEFAULT_CONFIG",
    "ERROR_CODES",
    "PERFORMANCE_THRESHOLDS",
    "QUALITY_LEVELS",
    "ENTITY_TYPES",
    "RELATIONSHIP_TYPES",
    "PROCESSING_STATUS",
    "DATA_TYPES",
    "API_ENDPOINTS",
    "FILE_SIZE_LIMITS",
    "RETRY_CONFIG",
    "CACHE_CONFIG",
    # Types
    "JSONType",
    "EntityDict",
    "RelationshipDict",
    "ConfigDict",
    "DataDict",
    "EntityType",
    "DataType",
    "ProcessingStatus",
    "QualityLevel",
    "RelationshipType",
    "Entity",
    "Relationship",
    "ProcessingResult",
    "QualityMetrics",
    "Result",
    "BatchResult",
    "is_entity_dict",
    "is_relationship_dict",
    "is_processing_result",
    "entity_to_dict",
    "dict_to_entity",
    "relationship_to_dict",
    "dict_to_relationship",
]